defmodule DndMatchmakerWeb.TestController do
  use DndMatchmakerWeb, :controller

  def show(conn, _params) do
    conn |> render(%{test: "This data was generated by my phoenix server"})
  end

  def reflect(conn, %{"data" => data}) do
    conn |> render(%{test: "This data is reflected by phoenix: " <> data})
  end
end
